#!/usr/bin/env node
import fs from "fs";
import path from "path";
import { branches, generateCategories, generateSites } from "../src/data/directory.js";

const outDir = path.join(process.cwd(), "public", "data");
fs.mkdirSync(outDir, { recursive: true });

const allCategories = [];
const allSites = [];

branches.forEach((branch) => {
  const categories = generateCategories(branch.id, branch.name);
  allCategories.push(...categories);

  categories.forEach((cat) => {
    const sites = generateSites(cat.id, cat.name, branch.id);
    allSites.push(...sites);
  });
});

fs.writeFileSync(path.join(outDir, "directory.json"), JSON.stringify({ branches, categories: allCategories }, null, 2));
fs.writeFileSync(path.join(outDir, "sites.json"), JSON.stringify(allSites, null, 2));

const tsDir = path.join(process.cwd(), "src", "data");
fs.mkdirSync(tsDir, { recursive: true });
fs.writeFileSync(
  path.join(tsDir, "generated.ts"),
  `// Auto-generated by generate-data.js
export const GENERATED_DIRECTORY = ${JSON.stringify({ branches, categories: allCategories, sites: allSites }, null, 2)} as const;
export default GENERATED_DIRECTORY;`
);

console.log("✅ Data generation complete.");
